//! The built-in reactive parser (plan §3.2): the pure grammar/replay/
//! snapshot machinery moved here from `src/component/parse`, with the
//! node-graph glue (`node.rs`, `context.rs`, `identity.rs` graph parts,
//! empty `generator.rs`) deleted.
//!
//! This module is the versioned home of the parser: `grammar.rs`,
//! `build.rs`, `types.rs`, `analyze.rs`, `diagnostics.rs`, `recovery.rs`,
//! `parser.rs`, `parsing/`, and `data/` all live under it.

pub(crate) mod analyze;
mod ast_walk;
pub(crate) mod build;
mod component;
pub mod data;
pub(crate) mod diagnostics;
pub mod grammar;
pub(crate) mod identity;
pub(crate) mod parser;
pub(crate) mod parsing;
pub(crate) mod recovery;
pub(crate) mod types;

#[doc(hidden)]
pub mod __macro_private;

pub use ast_walk::{AstWalk, AstWalkField};
pub use component::{
    ParseDiagnostics, ParseUnit, ParseUnits, ParserComponent, ParserCoreComponent, install_parser,
    install_parser_tree,
};
pub use data::ast::AstToken;
pub use data::green::{ErrorKind, ParseErrorInfo};
pub use identity::TokenFingerprint;
pub use parser::Parser;
pub use parsing::ParseError;
pub use types::{
    AstKey, AstLookupError, AstSnapshot, AstSnapshotEntry, AstTokenSnapshotEntry,
    IncrementalParseStats, ParseSnapshotId, ParseStatus, ParserConfig, ParserSnapshotState,
    ResolvedAst, TokenData, TokenOccurrenceId,
};

/// The family marker implemented by the root enum of every
/// `#[abstract_tree(members(...))]` family (generated by the macro). The
/// built-in parser component uses it to publish the family's tree view and
/// to walk the accepted root through the session arena.
pub trait AbstractTreeFamily: 'static {
    /// The payload union (one variant per member).
    type Node: Clone + Send + Sync + 'static;
    /// The typed case union.
    type Case: Clone + Send + Sync + 'static;
    /// The generated tree view of the family.
    type View: crate::reactive::view::ViewSpec;

    /// Emits the whole subtree with ids derived from source spans (parse
    /// path). The macro implements this by delegating to the root member's
    /// generated arena walker.
    #[doc(hidden)]
    fn __tree_walk_emit(
        handle: &crate::reactive::EmittedHandle<Self::View>,
        uri: &str,
        snapshot: &AstSnapshot,
        arena: &crate::framework::parse::data::AstArena,
        id: crate::reactive::view::NodeId,
        value: &Self,
    ) -> crate::reactive::Result<()>;

    /// The variant ordinal of one root value (spans the `kind` dimension
    /// of derived syntax ids).
    #[doc(hidden)]
    fn __tree_kind_of(value: &Self) -> u8;

    /// Derives one syntax node id from a source region.
    #[doc(hidden)]
    fn __tree_view_id(uri: &str, start: u32, end: u32, kind: u8) -> crate::reactive::view::NodeId;
}