[package]
name = "plingo"
version = "0.1.0"
edition = "2024"

[dependencies]

# Miscellaneous utilities
enum-iterator = "2.3.0"
fluent-uri = "0.4.1"

# For efficient data structures
smallvec = "1.15.1"
ropey = "1.6.1"
indexmap = "2.14.0"
bitvec = "1.0.1"

# For lexer
regex-syntax = "0.8.10"
regex-automata = "0.4.14"

# For async streams
async-stream = "0.3.6"
tokio-stream = "0.1.17"

# For logging
log = "0.4.29"
env_logger = "0.11.10"

# For error handling
anyhow = "1.0.102"
thiserror = "2.0.18"

# For macro development
plingo-macros = { path = "plingo-macros" }
color-print = "0.3.7"


[dependencies.tokio]
features = ["sync", "rt", "rt-multi-thread", "macros"]
version = "1.52.3"

[dev-dependencies]
notify = "8.2.0"
similar = "3.1.1"
workspace_root = "0.2.0"
