//! Source-aware semantic AST rendering generated by `Pretty*` derives.
//!
//! Grammar authors derive [`PrettyNonTerminal`] and [`PrettyTerminal`] next to
//! `NonTerminal` and `Terminal`; they never need to write a visitor or an AST
//! visualization adapter. [`AstTree`] retains the existing [`PrettyDisplay`]
//! integration, so a tree is rendered with `tree.pretty(&snapshot)`.

use std::fmt;

use color_print::cformat;

use crate::{
    component::parse::{AstLookupError, AstSnapshot, AstToken, data::AstBox, grammar::TerminalId},
    utils::PrettyDisplay,
};

/// Generated semantic rendering for a parser non-terminal.
pub trait PrettyNonTerminal {
    /// Render the active enum variant and its semantic children.
    fn pretty_non_terminal(&self, renderer: &mut AstRenderer<'_, '_>) -> fmt::Result;
}

/// Generated readable rendering for one terminal enum.
pub trait PrettyTerminal {
    /// Formats the terminal variant and exact source text from its snapshot.
    fn pretty_terminal(terminal: Option<TerminalId>, source: &str) -> String;
}

/// An AST root that can be formatted against an immutable parser snapshot.
///
/// The `PrettyNonTerminal` bound deliberately makes visualization a framework
/// feature of the derive, rather than an adapter each grammar author writes.
pub struct AstTree<T: PrettyNonTerminal> {
    root: AstBox<T>,
}

impl<T: PrettyNonTerminal> AstTree<T> {
    pub fn new(root: AstBox<T>) -> Self {
        Self { root }
    }

    pub fn root(&self) -> AstBox<T> {
        self.root
    }
}

impl<T: PrettyNonTerminal> From<AstBox<T>> for AstTree<T> {
    fn from(root: AstBox<T>) -> Self {
        Self::new(root)
    }
}

impl<T> PrettyDisplay<AstSnapshot> for AstTree<T>
where
    T: PrettyNonTerminal + Send + Sync + 'static,
{
    fn pretty_fmt(
        &self,
        formatter: &mut fmt::Formatter<'_>,
        snapshot: &AstSnapshot,
    ) -> fmt::Result {
        let mut renderer = AstRenderer::new(formatter, snapshot);
        renderer.node(self.root)
    }
}

/// Rendering context used by generated derive implementations.
///
/// This is public only because proc-macro expansions must name it. Its field
/// traversal methods are the stable extension point for generated code, not a
/// user-implemented visualization API.
pub struct AstRenderer<'snapshot, 'formatter> {
    formatter: &'formatter mut dyn fmt::Write,
    snapshot: &'snapshot AstSnapshot,
    depth: usize,
    active_span: Option<crate::utils::Span>,
}

impl<'snapshot, 'formatter> AstRenderer<'snapshot, 'formatter> {
    pub fn new(
        formatter: &'formatter mut dyn fmt::Write,
        snapshot: &'snapshot AstSnapshot,
    ) -> Self {
        Self {
            formatter,
            snapshot,
            depth: 0,
            active_span: None,
        }
    }

    /// Starts a generated enum-variant line and indents its fields.
    pub fn variant(
        &mut self,
        label: &str,
        render_fields: impl FnOnce(&mut Self) -> fmt::Result,
    ) -> fmt::Result {
        self.line(label, self.active_span)?;
        self.depth += 1;
        let result = render_fields(self);
        self.depth -= 1;
        result
    }

    /// Renders an AST-bearing field generated from an `AstBox`, `AstToken`,
    /// `Option`, `Vec`, or tuple containing those values.
    pub fn field<F: PrettyAstField>(&mut self, label: &str, field: &F) -> fmt::Result {
        self.indent()?;
        writeln!(
            self.formatter,
            "{}",
            cformat!("<dim>▸</> <yellow>{label}</>:")
        )?;
        self.depth += 1;
        let result = field.pretty_ast_field(self);
        self.depth -= 1;
        result
    }

    /// Renders parser error payloads and other non-AST semantic fields.
    pub fn debug_field(&mut self, label: &str, field: &impl fmt::Debug) -> fmt::Result {
        self.indent()?;
        writeln!(
            self.formatter,
            "{}",
            cformat!("<dim>▸</> <magenta>{label}</>: <dim>{field:?}</>")
        )
    }

    fn node<T>(&mut self, node: AstBox<T>) -> fmt::Result
    where
        T: PrettyNonTerminal + Send + Sync + 'static,
    {
        match self.snapshot.resolve(node) {
            Ok(value) => {
                let previous = self.active_span.replace(value.span());
                let result = value.pretty_non_terminal(self);
                self.active_span = previous;
                result
            }
            Err(error) => self.missing_node::<T>(node, error),
        }
    }

    fn token<T>(&mut self, token: AstToken<T>) -> fmt::Result
    where
        T: PrettyTerminal,
    {
        match self.snapshot.token(token) {
            Some(token) => {
                self.indent()?;
                writeln!(
                    self.formatter,
                    "{}",
                    cformat!(
                        "<green>{}</>",
                        T::pretty_terminal(token.terminal, &self.snapshot.source_text(token.span))
                    )
                )
            }
            None => {
                self.indent()?;
                writeln!(self.formatter, "<missing token#{}>", token.id)
            }
        }
    }

    fn missing_node<T>(&mut self, node: AstBox<T>, error: AstLookupError) -> fmt::Result {
        self.indent()?;
        writeln!(
            self.formatter,
            "<missing {} node#{}: {error}>",
            std::any::type_name::<T>(),
            node.id
        )
    }

    fn line(&mut self, label: &str, span: Option<crate::utils::Span>) -> fmt::Result {
        self.indent()?;
        match span {
            Some(span) => writeln!(
                self.formatter,
                "{}",
                cformat!(
                    "<bold,blue>{label}</> <dim>@{}</> <cyan>{:?}</>",
                    span,
                    self.snapshot.source_text(span)
                )
            ),
            None => writeln!(self.formatter, "{}", cformat!("<bold,blue>{label}</>")),
        }
    }

    fn indent(&mut self) -> fmt::Result {
        for _ in 0..self.depth {
            self.formatter.write_str("  ")?;
        }
        Ok(())
    }
}

/// Recursive AST field shapes understood by generated `PrettyNonTerminal`.
pub trait PrettyAstField {
    fn pretty_ast_field(&self, renderer: &mut AstRenderer<'_, '_>) -> fmt::Result;
}

impl<T> PrettyAstField for AstBox<T>
where
    T: PrettyNonTerminal + Send + Sync + 'static,
{
    fn pretty_ast_field(&self, renderer: &mut AstRenderer<'_, '_>) -> fmt::Result {
        renderer.node(*self)
    }
}

impl<T: PrettyTerminal> PrettyAstField for AstToken<T> {
    fn pretty_ast_field(&self, renderer: &mut AstRenderer<'_, '_>) -> fmt::Result {
        renderer.token(*self)
    }
}

impl<T: PrettyAstField> PrettyAstField for Option<T> {
    fn pretty_ast_field(&self, renderer: &mut AstRenderer<'_, '_>) -> fmt::Result {
        match self {
            Some(value) => value.pretty_ast_field(renderer),
            None => {
                renderer.indent()?;
                writeln!(renderer.formatter, "<none>")
            }
        }
    }
}

impl<T: PrettyAstField> PrettyAstField for Vec<T> {
    fn pretty_ast_field(&self, renderer: &mut AstRenderer<'_, '_>) -> fmt::Result {
        if self.is_empty() {
            renderer.indent()?;
            return writeln!(renderer.formatter, "<empty>");
        }
        for (index, value) in self.iter().enumerate() {
            renderer.indent()?;
            writeln!(renderer.formatter, "[{index}]:")?;
            renderer.depth += 1;
            let result = value.pretty_ast_field(renderer);
            renderer.depth -= 1;
            result?;
        }
        Ok(())
    }
}

macro_rules! tuple_fields {
    ($($index:literal: $name:ident),+) => {
        impl<$($name: PrettyAstField),+> PrettyAstField for ($($name,)+) {
            #[allow(non_snake_case)]
            fn pretty_ast_field(&self, renderer: &mut AstRenderer<'_, '_>) -> fmt::Result {
                let ($($name,)+) = self;
                $(
                    renderer.indent()?;
                    writeln!(renderer.formatter, "[{}]:", $index)?;
                    renderer.depth += 1;
                    let result = $name.pretty_ast_field(renderer);
                    renderer.depth -= 1;
                    result?;
                )+
                Ok(())
            }
        }
    };
}

tuple_fields!(0: A);
tuple_fields!(0: A, 1: B);
tuple_fields!(0: A, 1: B, 2: C);
tuple_fields!(0: A, 1: B, 2: C, 3: D);
